// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vZHOVAJxGzB-uPGY1UVRdwQwewoe9DI',
    appId: '1:12658043762:web:7bde5f2e90d61b949c0beb',
    messagingSenderId: '12658043762',
    projectId: 'e-commerce-app-3f2c5',
    authDomain: 'e-commerce-app-3f2c5.firebaseapp.com',
    storageBucket: 'e-commerce-app-3f2c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUjyOAVu_6oNbCMWgSh0v0qPJ6zG5trY',
    appId: '1:12658043762:android:d0285399d0cc7e8c9c0beb',
    messagingSenderId: '12658043762',
    projectId: 'e-commerce-app-3f2c5',
    storageBucket: 'e-commerce-app-3f2c5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1d1qqqIcwsqhSON26RwaeusAtfpZEN8',
    appId: '1:12658043762:ios:631254adf640ac389c0beb',
    messagingSenderId: '12658043762',
    projectId: 'e-commerce-app-3f2c5',
    storageBucket: 'e-commerce-app-3f2c5.firebasestorage.app',
    androidClientId: '12658043762-cj3lhu73ftlao1nhtfn5c7l4vcdtm2dd.apps.googleusercontent.com',
    iosClientId: '12658043762-m9aj7tknqt59ihvd9hc653m43nbcd0b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerStore',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1d1qqqIcwsqhSON26RwaeusAtfpZEN8',
    appId: '1:12658043762:ios:631254adf640ac389c0beb',
    messagingSenderId: '12658043762',
    projectId: 'e-commerce-app-3f2c5',
    storageBucket: 'e-commerce-app-3f2c5.firebasestorage.app',
    androidClientId: '12658043762-cj3lhu73ftlao1nhtfn5c7l4vcdtm2dd.apps.googleusercontent.com',
    iosClientId: '12658043762-m9aj7tknqt59ihvd9hc653m43nbcd0b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3vZHOVAJxGzB-uPGY1UVRdwQwewoe9DI',
    appId: '1:12658043762:web:3c3641732c9bc8499c0beb',
    messagingSenderId: '12658043762',
    projectId: 'e-commerce-app-3f2c5',
    authDomain: 'e-commerce-app-3f2c5.firebaseapp.com',
    storageBucket: 'e-commerce-app-3f2c5.firebasestorage.app',
  );
}
